name: Publish RSS feed

on:
 push:
    branches:
      - main
 workflow_dispatch:

jobs:
 build:
     runs-on: ubuntu-latest

     # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
     permissions:
       pages: write      # to deploy to Pages
       id-token: write   # to verify the deployment originates from an appropriate source

     # Deploy to the github-pages environment
     environment:
       name: github-pages
       url: ${{ steps.deployment.outputs.page_url }}

     steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: dorny/paths-filter@v3
        id: changes
        with: # Explanation: we might want to publish other files later, so add a generic publishedContent filter
          filters: |
            rss:
            - '*.xml'
            publishedContent:
            - '*.xml'

      - name: Validate feed.xml
        if: steps.changes.outputs.rss == 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-utils
          xmllint --noout ./feed.xml && echo "XML file validates"

      - name: Compile _site files
        if: steps.changes.outputs.publishedContent == 'true'
        run: |
         mkdir _site
         cp feed.xml _site/feed.xml

      - name: Upload _site directory
        if: steps.changes.outputs.publishedContent == 'true'
        uses: actions/upload-pages-artifact@v3.0.0

      - name: Deploy to GitHub Pages
        if: steps.changes.outputs.publishedContent == 'true'
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Update on pubsubhubbub
        if: steps.changes.outputs.rss == 'true'
        env:
          FEED_BASE_URL: ${{steps.deployment.outputs.page_url}}
        run: |
         echo $FEED_BASE_URL
         chmod +x ./pubsub.sh
         ./pubsub.sh
